- name: To deploy Version 2
  hosts: server
  become: yes

  tasks:
  - name: update nodejs and npm 
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - nodejs
      - npm
    become: yes
  - name: Copy the Artifacts
    ansible.builtin.copy:
      src: /home/jenkins/agent/workspace/build_task_yatin/nodejs-yatin1-0.0.3.tgz
      dest: /home/yatin/www2
    become_user: yatin
  - name: Unarchive the Artifacts
    command: "tar -xvf /home/yatin/www2/nodejs-yatin1-0.0.3.tgz -C /home/yatin/www2 "
    become_user: yatin
  - name: Copy the Service file
    ansible.builtin.copy:
      src: /home/jenkins/agent/workspace/build_task_yatin/nodejs.service
      dest: /etc/systemd/system
  - name: Enable app service
    command: systemctl enable nodejs
  - name: Start the app service
    command: systemctl restart nodejs
  - name: Print message
    ansible.builtin.debug:
      msg: Hello world