- name: To deploy Version 1
  hosts: server
  become: yes

  tasks:
  - name: Create Directory
    ansible.builtin.file:
      path: /home/yatin/www2
      state: directory
      mode: '0755' 
    become_user: yatin
  - name: Install nodejs and npm 
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - nodejs
      - npm
    become: yes
  - name: Copy the Artifacts
    ansible.builtin.copy:
      src: /home/jenkins/agent/workspace/build_task_yatin/nodejs-yatin1-0.0.1.tgz
      dest: /home/yatin/www2   
    become_user: yatin
  - name: Unarchive the Artifacts
    ansible.builtin.command:
      cmd: "tar -xvf /home/yatin/www2/nodejs-yatin1-0.0.1.tgz -C /home/yatin/www2 "
    become_user: yatin
  - name: Copy the Service file
    ansible.builtin.copy:
      src: /home/jenkins/agent/workspace/build_task_yatin/nodejs.service
      dest: /etc/systemd/system
  - name: Enable app service
    command: systemctl enable nodejs
  - name: Start the app service
    command: systemctl restart nodejs
  - name: Print message
    ansible.builtin.debug:
      msg: Hello world
