- name: My first play
  hosts: server
  become: yes
  tasks:
  - name: Create Directory
    ansible.builtin.file:
      path: /home/yatin/www1
      state: directory
      mode: '0755' 
  - name: Install nodejs and npm 
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - nodejs
      - npm
      - curl
    become: yes
  - name: Copy the Artifacts
    ansible.builtin.copy:
      src: /home/jenkins/agent/workspace/build_task_yatin/nodejs-yatin1-0.0.5.tgz
      dest: /home/yatin/www1
  - name: Unarchive the Artifacts
    ansible.builtin.unarchive:
      src: /home/yatin/www1/nodejs-yatin1-0.0.5.tgz
      dest: /home/yatin/www1
      remote_src: yes
  - name: Start app
    ansible.builtin.shell: |
      cd /home/yatin/www1/package && 
      pm2 reload all
  
  - name: Print message
    ansible.builtin.debug:
      msg: Hello world