- name: To deploy Version 2
  hosts: server
  become: yes

  tasks:
  - name: Copy the Artifacts
    ansible.builtin.copy:
      src: /home/jenkins/agent/workspace/build_task_yatin/nodejs-yatin1-0.0.3.tgz
      dest: /home/yatin/www2
    become_user: yatin
  - name: Unarchive the Artifacts
    ansible.builtin.unarchive:
      src: /home/yatin/www2/nodejs-yatin1-0.0.3.tgz
      dest: /home/yatin/www2
      remote_src: yes
    become_user: yatin
  - name: Start app
    command: pm2 reload all
    args:
      chdir: /home/yatin/www2/package
  - name: Print message
    ansible.builtin.debug:
      msg: Hello world