- name: My first play
  hosts: server
  become: yes

  tasks:
  - name: Create Directory
    ansible.builtin.file:
      path: /home/yatin/www2
      state: directory
      mode: '0755' 
    become_user: yatin
  - name: Install nodejs and npm 
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - nodejs
      - npm
      - curl
    become: yes
  - name: Copy the Artifacts
    ansible.builtin.copy:
      src: /home/jenkins/agent/workspace/build_task_yatin/nodejs-yatin1-0.0.5.tgz
      dest: /home/yatin/www2
    become_user: yatin
  - name: Unarchive the Artifacts
    ansible.builtin.unarchive:
      src: /home/yatin/www2/nodejs-yatin1-0.0.5.tgz
      dest: /home/yatin/www2
      remote_src: yes
    become_user: yatin
  - name: Start app
    command: pm2 start app.js
    args:
      chdir: /home/yatin/www2/package
  - name: Print message
    ansible.builtin.debug:
      msg: Hello world