- name: My first play
  hosts: server
  become: yes
  tasks:
  - name: Create Directory
    ansible.builtin.file:
      path: /home/yatin/www1
      state: directory
      mode: '0755' 
  - name: Install nodejs and npm 
    apt:
      pkg:
        - nodejs
        - npm

  - name: Copy the Artifacts
    ansible.builtin.copy:
      src: /home/jenkins/agent/workspace/build_task_yatin/nodejs-yatin1-0.0.4.tgz
      dest: /home/yatin/www
  - name: Unarchive the Artifacts
    ansible.builtin.unarchive:
      src: /home/yatin/www/nodejs-yatin1-0.0.4.tgz
      dest: /home/yatin/www
      remote_src: yes

  
  - name: Print message
    ansible.builtin.debug:
      msg: Hello world